export const BANGLADESH_POLICE_STATIONS: Record<string, string[]> = {
  Barishal: [
    "Agailjhara",
    "Airport",
    "Babuganj",
    "Bakerganj",
    "Banaripara",
    "Bandar",
    "Gournadi",
    "Hizla",
    "Kotwali",
    "Mehendiganj",
    "Muladi",
    "Wazirpur",
  ],
  Barguna: [
    "Amtali",
    "Bamna",
    "Barguna Sadar",
    "Betagi",
    "Patharghata",
    "Taltali",
  ],
  Bhola: [
    "Borhanuddin",
    "Char Fasson",
    "Daulatkhan",
    "Lalmohan",
    "Manpura",
    "Bhola Sadar",
    "Tazumuddin",
  ],
  Jhalokati: [
    "Jhalokati Sadar",
    "Kathalia",
    "Nalchity",
    "Rajapur",
  ],
  Patuakhali: [
    "Bauphal",
    "Dashmina",
    "Dumki",
    "Galachipa",
    "Kalapara",
    "Mirzaganj",
    "Patuakhali Sadar",
  ],
  Pirojpur: [
    "Bhandaria",
    "Kawkhali",
    "Mathbaria",
    "Nazirpur",
    "Nesarabad",
    "Pirojpur Sadar",
  ],
  Chattogram: [
    "Agrabad",
    "Akbar Shah",
    "Anwara",
    "Bakalia",
    "Bandar",
    "Banshkhali",
    "Bayezid Bostami",
    "Boalkhali",
    "Chandgaon",
    "Chandanaish",
    "Chawkbazar",
    "Double Mooring",
    "EPZ",
    "Fatikchhari",
    "Halishahar",
    "Hathazari",
    "Karnaphuli",
    "Khulshi",
    "Kotwali",
    "Lohagara",
    "Mirsharai",
    "Pahartali",
    "Panchlaish",
    "Patenga",
    "Patiya",
    "Rangunia",
    "Raozan",
    "Sadarghat",
    "Sandwip",
    "Satkania",
    "Sitakunda",
  ],
  Bandarban: [
    "Alikadam",
    "Bandarban Sadar",
    "Lama",
    "Naikhongchhari",
    "Rowangchhari",
    "Ruma",
    "Thanchi",
  ],
  Brahmanbaria: [
    "Akhaura",
    "Ashuganj",
    "Bancharampur",
    "Bijoynagar",
    "Brahmanbaria Sadar",
    "Kasba",
    "Nabinagar",
    "Nasirnagar",
    "Sarail",
  ],
  Chandpur: [
    "Chandpur Sadar",
    "Faridganj",
    "Haimchar",
    "Hajiganj",
    "Kachua",
    "Matlab Dakshin",
    "Matlab Uttar",
    "Shahrasti",
  ],
  Cumilla: [
    "Adarsha Sadar",
    "Barura",
    "Brahmanpara",
    "Burichang",
    "Chandina",
    "Chauddagram",
    "Cumilla Sadar Dakshin",
    "Daudkhandi",
    "Debidwar",
    "Homna",
    "Laksam",
    "Lalmai",
    "Meghna",
    "Monohargonj",
    "Muradnagar",
    "Nangalkot",
    "Titas",
  ],
  "Cox's Bazar": [
    "Chakaria",
    "Cox's Bazar Sadar",
    "Eidgaon",
    "Kutubdia",
    "Maheshkhali",
    "Pekua",
    "Ramu",
    "Teknaf",
    "Ukhia",
  ],
  Feni: [
    "Chhagalnaiya",
    "Daganbhuiyan",
    "Feni Sadar",
    "Fulgazi",
    "Parshuram",
    "Sonagazi",
  ],
  Khagrachhari: [
    "Baghaichhari",
    "Dighinala",
    "Khagrachhari Sadar",
    "Lakshmichhari",
    "Mahalchhari",
    "Manikchhari",
    "Matiranga",
    "Panchhari",
    "Ramgarh",
  ],
  Lakshmipur: [
    "Kamalnagar",
    "Lakshmipur Sadar",
    "Ramganj",
    "Ramgati",
    "Raipur",
  ],
  Noakhali: [
    "Begumganj",
    "Chatkhil",
    "Companiganj",
    "Hatiya",
    "Kabirhat",
    "Noakhali Sadar",
    "Senbagh",
    "Sonaimuri",
    "Subarnachar",
  ],
  Rangamati: [
    "Baghaichhari",
    "Barkal",
    "Belaichhari",
    "Juraichhari",
    "Kaptai",
    "Kaukhali",
    "Langadu",
    "Naniarchar",
    "Rajasthali",
    "Rangamati Sadar",
  ],
  Dhaka: [
    "Adabar",
    "Airport",
    "Ashulia",
    "Badda",
    "Banani",
    "Bangshal",
    "Bhashantek",
    "Bimanbandar",
    "Cantonment",
    "Chackbazar",
    "Dainik Bangla",
    "Dakshinkhan",
    "Darus Salam",
    "Demra",
    "Dhamrai",
    "Dhanmondi",
    "Dohar",
    "Gulshan",
    "Hatirjheel",
    "Hazaribagh",
    "Jatrabari",
    "Kadamtali",
    "Kafrul",
    "Kalabagan",
    "Kamrangirchar",
    "Keraniganj",
    "Khilgaon",
    "Khilkhet",
    "Kotwali",
    "Lalbagh",
    "Mirpur",
    "Mohammadpur",
    "Motijheel",
    "Mugda",
    "Nawabganj",
    "New Market",
    "Pallabi",
    "Paltan",
    "Purbachal",
    "Ramna",
    "Rampura",
    "Rupnagar",
    "Sabujbagh",
    "Savar",
    "Savar Model",
    "Shah Ali",
    "Shahbagh",
    "Shahjahanpur",
    "Sher-e-Bangla Nagar",
    "Sutrapur",
    "Shyampur",
    "Tejgaon",
    "Tejgaon Industrial Area",
    "Turag",
    "Uttara East",
    "Uttara Paschim",
    "Uttara West",
    "Uttar Khan",
    "Vatara",
    "Wari",
    "Agargaon",
    "CMP Complex",
    "National Assembly Area",
    "Chandrima Udyan",
    "West Agargaon",
    "T&T Colony",
    "Shyamoli",
    "Sher-e-Bangla Nagar Administrative Area",
    "Dhanmondi R/A",
    "Panthapath",
    "Sukrabad",
    "Green Road",
    "Kathalbagan",
    "Sobhanbag",
    "Shankar",
    "Zigatola",
    "Lake Circus",
    "North Dhanmondi",
    "Bashiruddin Road",
    "Free School Street",
    "Tannery Area",
    "Rayer Bazar",
    "Sultanganj",
    "Ganaktuli",
    "Enayetganj",
    "Zafrabad",
    "Bhagalpur",
    "Nilkhet",
    "Azimpur",
    "Dhaka University Campus",
    "Chandrima Super Market Area",
    "Elephant Road",
    "Pilkhana",
    "Mohammadpur Town Hall",
    "Asad Gate",
    "Iqbal Road",
    "Taj Mahal Road",
    "Humayun Road",
    "Babar Road",
    "Salimullah Road",
    "Sir Syed Road",
    "Ring Road",
    "Japan Garden City",
    "Noorjahan Road",
    "Geneva Camp",
    "Mohammadpur Housing Estate",
    "Adabor",
    "Baitul Aman Housing",
    "Sun Valley Housing",
    "Mansurabad",
    "Nabodoy Housing",
    "PC Culture Housing",
    "Shekertek",
    "Sunibir Housing",
    "Chand Udyan",
    "Shyamoli Housing",
    "Farmgate",
    "Tejkunipara",
    "West Nakhalpara",
    "Indira Road",
    "Monipuripara",
    "Rajabazar",
    "Kawran Bazar",
    "East Nakhalpara",
    "Nabisco",
    "Tibet Intersection",
    "Kunipara",
    "Channel i Area",
    "Shaheed Tajuddin Ahmed Sarani",
    "Ramna Park",
    "Suhrawardy Udyan",
    "Kakrail",
    "Eskaton",
    "Siddheswari",
    "Malibagh",
    "Moghbazar",
    "Segunbagicha",
    "Baily Road",
    "Dhaka Medical College Hospital Campus",
    "BSMMU Campus",
    "Topkhana Road",
    "Matsya Bhaban Area",
    "High Court Area",
    "Curzon Hall Campus",
    "Naya Paltan",
    "Purana Paltan",
    "Purana Paltan Line",
    "Bijoynagar",
    "Press Club Area",
    "Bangladesh Bank Area",
    "Dainik Bangla Intersection",
    "Motijheel Commercial Area",
    "Dilkusha",
    "Arambagh",
    "Fakirapool",
    "Kamalapur",
    "RK Mission Road",
    "Bangladesh Bank Colony",
    "Railway Colony",
    "West Malibagh",
    "Gulbagh",
    "Khilgaon Railway Gate Area",
    "Santinagar",
    "West Rampura",
    "TV Center Area",
    "Mohanagar Project",
    "Banasree",
    "DIT Road",
    "East Rampura",
    "Hajipara",
    "Hatirjheel Promenade",
    "Dilu Road",
    "Madhubag",
    "Wireless Jhilpar",
    "Neyamatullah Road",
    "Nayatola",
    "Begunbari",
    "Middle Badda",
    "North Badda",
    "South Badda",
    "Merul Badda",
    "DIT Project Badda",
    "Aftabnagar",
    "Satarkul",
    "Bashundhara Residential Area",
    "Nurer Chala",
    "Saidnagar",
    "Kuril",
    "Solmaid",
    "Jagannathpur",
    "Nikunja 1",
    "Nikunja 2",
    "Kuratoli",
    "Pink City",
    "Dumni",
    "Namapara",
    "Tanpara",
    "Mastul",
    "Joar Sahara",
    "Uttara Sector 1",
    "Uttara Sector 2",
    "Uttara Sector 3",
    "Uttara Sector 4",
    "Uttara Sector 5",
    "Uttara Sector 6",
    "Uttara Sector 7",
    "Uttara Sector 8",
    "Uttara Sector 9",
    "Uttara Sector 10",
    "Uttara Sector 11",
    "Uttara Sector 12",
    "Uttara Sector 13",
    "Uttara Sector 14",
    "Uttara Sector 15",
    "Uttara Sector 16",
    "Uttara Sector 17",
    "Uttara Sector 18",
    "Sonargaon Janapath",
    "Azampur",
    "Abdullahpur",
    "Uttarkhan",
    "Masterpara",
    "Uzampur",
    "Mollartek",
    "Faydabad",
    "Kuripara",
    "Helal Bhaban Area",
    "Gawair",
    "KC Hospital Area",
    "Prembagan",
    "Ashkona",
    "Chalabon",
    "Kamarpara",
    "Dhalpur",
    "Nolbhog",
    "Ranavola",
    "Dhanaia",
    "Chandertek",
    "Hazrat Shahjalal International Airport Campus",
    "Civil Aviation Colony",
    "Kawla",
    "Ashkona Hajj Camp Area",
    "Gulshan 1",
    "Gulshan 2",
    "Niketan",
    "Baridhara Diplomatic Zone",
    "Baridhara J-Block",
    "Mohakhali DOHS",
    "Banani DOHS",
    "Chairman Bari",
    "Kakoli",
    "Amtoli",
    "Korail Area",
    "Kemal Ataturk Avenue",
    "Dhaka Cantonment",
    "Matikata",
    "ECB Circle",
    "Staff Road",
    "Zia Colony",
    "Nirjhor Residential Area",
    "Vashantek",
    "Damalkot",
    "Dewanpara",
    "Jamgarah",
    "Senpara Parbata",
    "Ibrahimpur",
    "Kazipara",
    "Shewrapara",
    "Mirpur Section 1",
    "Mirpur Section 2",
    "Mirpur Section 10",
    "Mirpur Section 11",
    "Mirpur Section 12",
    "Mirpur Section 14",
    "Duaripara",
    "Kalshi",
    "Muslim Bazar",
    "Bauniabadh",
    "Eastern Housing Mirpur",
    "Shah Ali Bag",
    "Golartek",
    "Botanical Garden Area",
    "National Zoo Area",
    "Mirpur Beribadh",
    "Technical Intersection",
    "Gabtoli",
    "Kallyanpur",
    "Paikpara",
    "Tolarbag",
    "Ananda Nagar",
    "Taltola",
    "Goran",
    "Sipahibagh",
    "Nandipara",
    "Trimohani",
    "Tilpapara",
    "Basabo",
    "Kadamtala",
    "Madartek",
    "Wahidpur",
    "Rajarbagh",
    "Mayanagar",
    "South Mugda",
    "North Mugda",
    "Mugda Hospital Area",
    "Manda",
    "Maniknagar",
    "North Jatrabari",
    "South Jatrabari",
    "Sayedabad",
    "Dholaipar",
    "Kutubkhali",
    "Bibir Bagicha",
    "Kazla",
    "Konapara",
    "Matuail",
    "Dania",
    "Sarulia",
    "Staff Quarter Demra",
    "Amrakani",
    "Bamail",
    "Dogair",
    "Jurain",
    "Rayerbagh",
    "Shani Akhra",
    "Dhalka Nagar",
    "Merajnagar",
    "Shyampur Industrial Area",
    "Faridabad",
    "IG Gate",
    "Postogola",
    "Palaspur",
    "West Jurain",
    "Gandaria",
    "Dhupkhola",
    "Dinanath Sen Road",
    "Mill Barrack",
    "Dayaganj",
    "Distillery Road",
    "Rajani Chowdhury Road",
    "Malitola",
    "Farashganj",
    "Laxmibazar",
    "Bangla Bazar",
    "Shakhari Bazar",
    "Wiseghat",
    "Jhiltuly",
    "Islampur",
    "Babu Bazar",
    "Sadarghat",
    "Mitford",
    "Patuatuly",
    "Chhitakatan",
    "Badamtali",
    "Bangsal",
    "Nawabpur Road",
    "Siddique Bazar",
    "English Road",
    "Kazi Alauddin Road",
    "Alu Bazar",
    "Chawkbazar",
    "Urdu Road",
    "Begum Bazar",
    "Water Works Road",
    "Imamganj",
    "Posta",
    "Hosni Dalan Area",
    "Mogaltuly",
    "Lalbagh Fort Area",
    "Azimpur Estate",
    "Dhakeshwari",
    "Jagannath Saha Road",
    "Subhash Bose Avenue",
    "Shaheed Nagar",
    "Pushporaj Saha Lane",
    "Ashrafabad",
    "Rasulpur",
    "Jhauchar",
    "Barogram",
    "Munshihati",
    "Borakhyal",
    "Companyghat",
    "Iron Bridge Area",
    "Rankin Street",
    "Hare Street",
    "Larmini Street",
    "Tikatuly",
    "Hatkhola",
    "KM Das Lane",
    "Gopibagh"
  ],
  Faridpur: [
    "Alfadanga",
    "Bhanga",
    "Boalmari",
    "Charbhadrasan",
    "Faridpur Sadar",
    "Madhukhali",
    "Nagarkanda",
    "Sadarpur",
    "Saltha",
  ],
  Gazipur: [
    "Bason",
    "Gazipur Sadar",
    "Kaliakair",
    "Kaliganj",
    "Kapasia",
    "Kashimpur",
    "Konabari",
    "Sreepur",
    "Tongi",
    "Tongi East",
    "Tongi West",
    "Joydebpur",
    "Chandna",
    "Chourasta",
    "Shibbari",
    "Rajbari",
    "Bhawal Mirzapur",
    "Mogarkhal",
    "Bhaduriyapara",
    "Salna",
    "Bhawal National Park",
    "Islampur",
    "Konabari BSCIC",
    "Nilnagar",
    "Jarun",
    "Sarabo",
    "Baimail",
    "Baghabari",
    "Enamnagar",
    "Board Bazar",
    "National University",
    "Open University",
    "Taratpara",
    "Gacha",
    "Kunia",
    "Pubail",
    "Mazukhan",
    "Mirer Bazar",
    "Santanpara",
    "Station Road",
    "Monnunagar",
    "College Gate",
    "Cherag Ali",
    "Ershad Nagar",
    "Gazipura",
    "Auchpara",
    "Tari Bazar",
    "Mill Gate",
    "Satish Sarker Road",
    "Safipur",
    "Mouchak",
    "Chapair",
    "Sutrapur",
    "Boali",
    "Fulbaria",
    "Dhaljora",
    "Madhabpur",
    "Atabaha",
    "Nagari",
    "Tumulia",
    "Bhawal Jamalpur",
    "Moktarpur",
    "Bahadurpur",
    "Jangalia",
    "Toke",
    "Rayed",
    "Karihabata",
    "Sanmania",
    "Ghagotia",
    "Chandpur",
    "Kitosania",
    "Barisabo",
    "Durga Pur",
    "Mawna",
    "Rajendrapur",
    "Rajendrapur Cantonment",
    "Barmi",
    "Kawraid",
    "Telihati",
    "Prahladpur"
  ],
  Gopalganj: [
    "Gopalganj Sadar",
    "Kashiani",
    "Kotalipara",
    "Muksudpur",
    "Tungipara",
  ],
  Kishoreganj: [
    "Austagram",
    "Bajitpur",
    "Bhairab",
    "Hossainpur",
    "Itna",
    "Karimganj",
    "Katiadi",
    "Kishoreganj Sadar",
    "Kuliarchar",
    "Mithamain",
    "Nikli",
    "Pakundia",
    "Tarail",
  ],
  Madaripur: [
    "Dasar",
    "Kalkini",
    "Madaripur Sadar",
    "Rajoir",
    "Shibchar",
  ],
  Manikganj: [
    "Daulatpur",
    "Ghior",
    "Harirampur",
    "Manikganj Sadar",
    "Saturia",
    "Shibalaya",
    "Singair",
  ],
  Munshiganj: [
    "Gazaria",
    "Lohajang",
    "Munshiganj Sadar",
    "Sirajdikhan",
    "Sreenagar",
    "Tongibari",
  ],
  Narayanganj: [
    "Adamjee",
    "Araihazar",
    "Bandar",
    "Narayanganj Kotwali",
    "Narayanganj Sadar",
    "Rupganj",
    "Sonargaon",
    "Chasara",
    "Tanbazar",
    "Nitayganj",
    "Ukilpara",
    "Deobhog",
    "Khanpur",
    "Masdair",
    "Paikpara",
    "Fatullah",
    "Panchabati",
    "Bhuigar",
    "Kutubpur",
    "Enayetnagar",
    "Kashipur",
    "Pagla",
    "Jalkuri",
    "Adamjee EPZ",
    "Adamjeenagar",
    "Mizmizi",
    "Godnayel",
    "LN Mills",
    "Siddhirganj",
    "Nabiganj",
    "Kadamrasul",
    "Madanganj",
    "Sonakanda",
    "Dhakeshwari",
    "Dhamgarh",
    "Bhulta",
    "Gauchia",
    "Kanchan",
    "Murapara",
    "Tarabo",
    "Nagri",
    "Purbachal",
    "Daudpur",
    "Gopaldi",
    "Satgram",
    "Duptara",
    "Brahmandi",
    "Highakar",
    "Fatehpur",
    "Bishnandi",
    "Mahmudpur",
    "Panam City",
    "Mograpara",
    "Baidder Bazar",
    "Barodi",
    "Kanchpur",
    "Aminpur",
    "Jampur",
    "Noagaon",
    "Sanmandi",
    "Shambhupura"
  ],
  Narsingdi: [
    "Belabo",
    "Monohardi",
    "Narsingdi Sadar",
    "Palash",
    "Raipura",
    "Shibpur",
  ],
  Rajbari: [
    "Baliakandi",
    "Goalandaghat",
    "Kalukhali",
    "Pangsha",
    "Rajbari Sadar",
  ],
  Shariatpur: [
    "Bhedarganj",
    "Damudya",
    "Gosairhat",
    "Naria",
    "Shariatpur Sadar",
    "Zajira",
  ],
  Tangail: [
    "Basail",
    "Bhuapur",
    "Delduar",
    "Dhanbari",
    "Ghatail",
    "Gopalpur",
    "Kalihati",
    "Madhupur",
    "Mirzapur",
    "Nagarpur",
    "Sakhipur",
    "Tangail Sadar",
  ],
  Khulna: [
    "Batiaghata",
    "Daulatpur",
    "Dighalia",
    "Dumuria",
    "Horintana",
    "Khanjahan Ali",
    "Khalishpur",
    "Kotwali",
    "Paikgachha",
    "Phultala",
    "Rupsa",
    "Sonadanga",
    "Terokhada",
  ],
  Bagerhat: [
    "Bagerhat Sadar",
    "Chitalmari",
    "Fakirhat",
    "Kachua",
    "Mollahat",
    "Mongla",
    "Morrelganj",
    "Rampal",
    "Sarankhola",
  ],
  Chuadanga: [
    "Alamdanga",
    "Chuadanga Sadar",
    "Damurhuda",
    "Jibannagar",
  ],
  Jashore: [
    "Abhaynagar",
    "Bagherpara",
    "Chaugachha",
    "Jashore Sadar",
    "Jhikargachha",
    "Keshabpur",
    "Manirampur",
    "Sharsha",
  ],
  Jhenaidah: [
    "Harinakunda",
    "Jhenaidah Sadar",
    "Kaliganj",
    "Kotchandpur",
    "Maheshpur",
    "Shailkupa",
  ],
  Kushtia: [
    "Bheramara",
    "Daulatpur",
    "Khoksa",
    "Kumarkhali",
    "Kushtia Kotwali",
    "Kushtia Sadar",
    "Mirpur",
  ],
  Magura: [
    "Magura Sadar",
    "Mohammadpur",
    "Shalikha",
    "Sreepur",
  ],
  Meherpur: [
    "Gangni",
    "Meherpur Sadar",
    "Mujibnagar",
  ],
  Narail: [
    "Kalia",
    "Lohagara",
    "Narail Sadar",
  ],
  Satkhira: [
    "Assasuni",
    "Debhata",
    "Kalaroa",
    "Kaliganj",
    "Satkhira Sadar",
    "Shyamnagar",
    "Tala",
  ],
  Mymensingh: [
    "Bhaluka",
    "Dhobaura",
    "Fulbaria",
    "Gafargaon",
    "Gauripur",
    "Haluaghat",
    "Ishwarganj",
    "Muktagachha",
    "Mymensingh Kotwali",
    "Mymensingh Sadar",
    "Mymensingh Sadar Bazar",
    "Nandail",
    "Phulpur",
    "Trishal",
  ],
  Jamalpur: [
    "Baksiganj",
    "Dewanganj",
    "Islampur",
    "Jamalpur Kotwali",
    "Jamalpur Sadar",
    "Madarganj",
    "Melandaha",
    "Sarishabari",
  ],
  Netrokona: [
    "Atpara",
    "Barhatta",
    "Durgapur",
    "Kalmakanda",
    "Kendua",
    "Khaliajuri",
    "Madan",
    "Mohanganj",
    "Netrokona Sadar",
    "Purbadhala",
  ],
  Sherpur: [
    "Jhenaigati",
    "Nakla",
    "Nalitabari",
    "Sherpur Kotwali",
    "Sherpur Sadar",
    "Sreebardi",
  ],
  Rajshahi: [
    "Bagha",
    "Bagmara",
    "Boalia",
    "Charghat",
    "Durgapur",
    "Godagari",
    "Mohanpur",
    "Motihar",
    "Paba",
    "Puthia",
    "Rajpara",
    "Rajshahi Sadar",
    "Tanore",
  ],
  Bogura: [
    "Adamdighi",
    "Bogura Sadar",
    "Dhunat",
    "Dhupchanchia",
    "Gabtali",
    "Kahaloo",
    "Nandigram",
    "Sariakandi",
    "Shajahanpur",
    "Sherpur",
    "Shibganj",
    "Sonatala",
  ],
  Chapainawabganj: [
    "Bholahat",
    "Chapainawabganj Sadar",
    "Gomastapur",
    "Nachole",
    "Shibganj",
  ],
  Joypurhat: [
    "Akkelpur",
    "Joypurhat Sadar",
    "Kalai",
    "Khetlal",
    "Panchbibi",
  ],
  Naogaon: [
    "Atrai",
    "Badalgachhi",
    "Dhamoirhat",
    "Manda",
    "Mohadevpur",
    "Naogaon Sadar",
    "Niamatpur",
    "Patnitala",
    "Porsha",
    "Raninagar",
    "Sapahar",
  ],
  Natore: [
    "Bagatipara",
    "Baraigram",
    "Gurudaspur",
    "Lalpur",
    "Naldanga",
    "Natore Sadar",
    "Singra",
  ],
  Pabna: [
    "Atgharia",
    "Bera",
    "Bhangura",
    "Chatmohar",
    "Faridpur",
    "Ishwardi",
    "Pabna Kotwali",
    "Pabna Sadar",
    "Santhia",
    "Sujanagar",
  ],
  Sirajganj: [
    "Belkuchi",
    "Chauhali",
    "Kamarkhanda",
    "Kazipur",
    "Royganj",
    "Shahjadpur",
    "Sirajganj Sadar",
    "Tarash",
    "Ullahpara",
  ],
  Rangpur: [
    "Badarganj",
    "Gangachara",
    "Kaunia",
    "Mithapukur",
    "Pirgachha",
    "Pirganj",
    "Rangpur Sadar",
    "Taraganj",
  ],
  Dinajpur: [
    "Birampur",
    "Birganj",
    "Biral",
    "Bochaganj",
    "Chirirbandar",
    "Dinajpur Sadar",
    "Fulbari",
    "Ghoraghat",
    "Hakimpur",
    "Kaharole",
    "Khansama",
    "Nawabganj",
    "Parbatipur",
  ],
  Gaibandha: [
    "Fulchhari",
    "Gaibandha Sadar",
    "Gobindaganj",
    "Palashbari",
    "Sadullapur",
    "Saghata",
    "Sundarganj",
  ],
  Kurigram: [
    "Bhurungamari",
    "Char Rajibpur",
    "Chilmari",
    "Kurigram Sadar",
    "Nageshwari",
    "Phulbari",
    "Rajarhat",
    "Raomari",
    "Ulipur",
  ],
  Lalmonirhat: [
    "Aditmari",
    "Hatibandha",
    "Kaliganj",
    "Lalmonirhat Sadar",
    "Patgram",
  ],
  Nilphamari: [
    "Dimla",
    "Domar",
    "Jaldhaka",
    "Kishoreganj",
    "Nilphamari Sadar",
    "Saidpur",
  ],
  Panchagarh: [
    "Atwari",
    "Boda",
    "Debiganj",
    "Panchagarh Sadar",
    "Tetulia",
  ],
  Thakurgaon: [
    "Baliadangi",
    "Haripur",
    "Pirganj",
    "Ranisankail",
    "Thakurgaon Sadar",
  ],
  Sylhet: [
    "Balaganj",
    "Beanibazar",
    "Bishwanath",
    "Companiganj",
    "Dakshin Surma",
    "Fenchuganj",
    "Golapganj",
    "Gowainghat",
    "Jaintiapur",
    "Kanaighat",
    "Sylhet Kotwali",
    "Sylhet Sadar",
    "Zakiganj",
  ],
  Habiganj: [
    "Ajmiriganj",
    "Bahubal",
    "Baniachong",
    "Chunarughat",
    "Habiganj Sadar",
    "Lakhai",
    "Madhabpur",
    "Nabiganj",
  ],
  Moulvibazar: [
    "Barlekha",
    "Juri",
    "Kamalganj",
    "Kulaura",
    "Moulvibazar Sadar",
    "Rajnagar",
    "Sreemangal",
  ],
  Sunamganj: [
    "Bishwamvarpur",
    "Chhatak",
    "Derai",
    "Dharamapasha",
    "Dowarabazar",
    "Jagannathpur",
    "Jamalganj",
    "Sullah",
    "Shantiganj",
    "Sunamganj Sadar",
    "Tahirpur",
  ],
}
