export const PROJECT_TENDER_CATEGORIES = [
  "Machine",
  "Consumable",
  "Solution",
  "Machine + Consumable",
  "Machine + Solution",
  "Consumable + Solution",
  "All",
]

export const BANGLADESH_DISTRICTS = [
  "Barishal",
  "Barguna",
  "Bhola",
  "Jhalokati",
  "Patuakhali",
  "Pirojpur",
  "Chattogram",
  "Bandarban",
  "Brahmanbaria",
  "Chandpur",
  "Cumilla",
  "Cox's Bazar",
  "Feni",
  "Khagrachhari",
  "Lakshmipur",
  "Noakhali",
  "Rangamati",
  "Dhaka",
  "Faridpur",
  "Gazipur",
  "Gopalganj",
  "Kishoreganj",
  "Madaripur",
  "Manikganj",
  "Munshiganj",
  "Narayanganj",
  "Narsingdi",
  "Rajbari",
  "Shariatpur",
  "Tangail",
  "Khulna",
  "Bagerhat",
  "Chuadanga",
  "Jashore",
  "Jhenaidah",
  "Kushtia",
  "Magura",
  "Meherpur",
  "Narail",
  "Satkhira",
  "Mymensingh",
  "Jamalpur",
  "Netrokona",
  "Sherpur",
  "Rajshahi",
  "Bogura",
  "Chapainawabganj",
  "Joypurhat",
  "Naogaon",
  "Natore",
  "Pabna",
  "Sirajganj",
  "Rangpur",
  "Dinajpur",
  "Gaibandha",
  "Kurigram",
  "Lalmonirhat",
  "Nilphamari",
  "Panchagarh",
  "Thakurgaon",
  "Sylhet",
  "Habiganj",
  "Moulvibazar",
  "Sunamganj",
]
